version: '3'

networks:
  laravelapp:
    driver: bridge

services:
  phpfpm:
    build:
      context: .
      dockerfile: ./.docker/php-fpm/Dockerfile
    tty: true
    restart: always
    volumes:
      - ./:/var/www
    working_dir: /var/www
    networks:
      - laravelapp

  database:
    image: mysql:8.0.30
    tty: true
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db_name
      MYSQL_USER: laravel_db_user
      MYSQL_PASSWORD: laravel_db_pass
    ports:
    - 3306:3306
    volumes:
      - ./.docker/db/:/var/lib/mysql
    networks:
      - laravelapp

  webserver:
    image: nginx:1.24.0
    restart: always
    tty: true
    depends_on:
      - phpfpm
    ports:
      - "8001:80"
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/index.html:/usr/share/nginx/html/index.html
      - ./:/var/www
    working_dir: /var/www
    networks:
      - laravelapp
